version: '3.8'

services:
  book-service:
    build:
      context: .
      dockerfile: Dockerfile.book
    ports:
      - "8081:8081"
    networks:
      - flingo-network

  progress-service:
    build:
      context: .
      dockerfile: Dockerfile.progress
    ports:
      - "8082:8082"
    networks:
      - flingo-network

  rating-service:
    build:
      context: .
      dockerfile: Dockerfile.rating
    ports:
      - "8083:8083"
    networks:
      - flingo-network

networks:
  flingo-network:
    driver: bridge
